name: main
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        test-type: ["small", "large"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: run tests
        if: matrix.test-type == 'large' && (matrix.python-version == '3.9' || matrix.python-version == '3.10')
        run: poetry run pytest -s -v --junitxml=${{ matrix.test-type }}_${{matrix.python-version}}_tests_results.xml tests/${{ matrix.test-type }}
      - uses: actions/upload-artifact@v3
        if: matrix.test-type == 'small'
        with:
          name: small_tests
          path: |
            ./
            ./
            !/**/*small*.xml
      - uses: actions/upload-artifact@v3
        with:
          name: large_tests
          path: |
            ./
            ./
            !/**/*large*.xml

  report_workflow:
    if: always()
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1
        with:
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
